apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-clickhouse-server-config-d-common
data:
  zookeeper.xml: |-
    <yandex>
        <zookeeper>
            <node>
                <host>zookeeper-service-client</host>
                <port>2181</port>
            </node>
        </zookeeper>
    </yandex>

  remote_servers.xml: |-
    <yandex>
        <remote_servers>

            <benchmark_cluster>
                <shard>
                    <replica>
                        <!-- chpod1 -->
                        <host>chpod1.chpod-hs.default.svc.cluster.local</host>
                        <port>9000</port>
                    </replica>
                </shard>
                <shard>
                    <replica>
                        <!-- chpod2 -->
                        <host>chpod2.chpod-hs.default.svc.cluster.local</host>
                        <port>9000</port>
                    </replica>
                </shard>
            </benchmark_cluster>

            <repl_cluster>
                <shard>
                    <internal_replication>true</internal_replication>
                    <replica>
                        <!-- chpod1 -->
                        <host>chpod1.chpod-hs.default.svc.cluster.local</host>
                        <port>9000</port>
                    </replica>
                    <replica>
                        <!-- chpod3 -->
                        <host>chpod3.chpod-hs.default.svc.cluster.local</host>
                        <port>9000</port>
                    </replica>
                </shard>
                <shard>
                    <internal_replication>true</internal_replication>
                    <replica>
                        <!-- chpod2 -->
                        <host>chpod2.chpod-hs.default.svc.cluster.local</host>
                        <port>9000</port>
                    </replica>
                    <replica>
                        <!-- chpod4 -->
                        <host>chpod4.chpod-hs.default.svc.cluster.local</host>
                        <port>9000</port>
                    </replica>
                </shard>
            </repl_cluster>

        </remote_servers>
    </yandex>

