apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-clickhouse-server-config-d-macros-chpod3
data:
  macros.xml: |-
    <yandex>
        <macros>
            <shard>1</shard>
            <replica>2</replica>
        </macros>
    </yandex>
---
apiVersion: v1
kind: Pod
metadata:
  name: chpod3
  labels:
    app: chpod3
    dns: chi1
spec:
  hostname: chpod3
  subdomain: chpod-hs
  containers:
  - name: chpod3
    image: yandex/clickhouse-server
    livenessProbe:
      tcpSocket:
        port: 8123
#        port: 9000
      initialDelaySeconds: 10
      periodSeconds: 10
    readinessProbe:
      exec:
        command:
        - /bin/bash
        - -c
        - clickhouse-client -q 'select version()' && [ $(wget localhost:8123 -q -O /dev/stdout) == 'Ok.' ]
      initialDelaySeconds: 20
      periodSeconds: 20
    volumeMounts:
    - name: etc-clickhouse-server-config-d-common-volume
      mountPath: /etc/clickhouse-server/config.d/remote_servers.xml
      subPath: remote_servers.xml
    - name: etc-clickhouse-server-config-d-common-volume
      mountPath: /etc/clickhouse-server/config.d/zookeeper.xml
      subPath: zookeeper.xml
    - name: etc-clickhouse-server-config-d-macros-volume
      mountPath: /etc/clickhouse-server/config.d/macros.xml
      subPath: macros.xml
  volumes:
  - name: etc-clickhouse-server-config-d-common-volume
    configMap:
      name: etc-clickhouse-server-config-d-common
  - name: etc-clickhouse-server-config-d-macros-volume
    configMap:
      name: etc-clickhouse-server-config-d-macros-chpod3

