apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-clickhouse-server-config-d-macros-chpod1
data:
  macros.xml: |-
    <yandex>
        <macros>
            <shard>1</shard>
            <replica>1</replica>
        </macros>
    </yandex>
---
apiVersion: v1
kind: Pod
metadata:
  name: chpod1
  labels:
    app: chpod1
    dns: chi1
spec:
  hostname: chpod1
  subdomain: chpod-hs
  containers:
  - name: chpod1
    image: yandex/clickhouse-server
    volumeMounts:
    - name: etc-clickhouse-server-config-d-common-volume
      mountPath: /etc/clickhouse-server/config.d/remote_servers.xml
      subPath: remote_servers.xml
    - name: etc-clickhouse-server-config-d-common-volume
      mountPath: /etc/clickhouse-server/config.d/zookeeper.xml
      subPath: zookeeper.xml
    - name: etc-clickhouse-server-config-d-macros-volume
      mountPath: /etc/clickhouse-server/config.d/macros.xml
      subPath: macros.xml
  volumes:
  - name: etc-clickhouse-server-config-d-common-volume
    configMap:
      name: etc-clickhouse-server-config-d-common
  - name: etc-clickhouse-server-config-d-macros-volume
    configMap:
      name: etc-clickhouse-server-config-d-macros-chpod2

