# Possible Template Parameters:
#
# kube-system
# altinity/clickhouse-operator:latest
#
# Setup CustomResourceDefinition
# CustomResourceDefinition is namespace-less and must have unique name
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clickhouseinstallations.clickhouse.altinity.com
spec:
  group: clickhouse.altinity.com
  version: v1
  scope: Namespaced
  names:
    kind: ClickHouseInstallation
    singular: clickhouseinstallation
    plural: clickhouseinstallations
    shortNames:
      - chi
  additionalPrinterColumns:
    - name: version
      type: string
      description: Operator version
      JSONPath: .status.version
    - name: clusters
      type: integer
      description: Clusters number
      JSONPath: .status.clustersCount
    - name: replicas
      type: integer
      description: Replicas count
      JSONPath: .status.replicasCount
    - name: endpoint
      type: string
      description: Client access endpoint
      JSONPath: .status.endpoint
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          required:
            - configuration
          properties:
            defaults:
              type: object
              properties:
                replicasUseFQDN:
                  enum:
                    - 0
                    - 1
                    - False
                    - True
                    - No
                    - Yes
                    - Off
                    - On
                    - Disabled
                    - Enabled
                distributedDDL:
                  type: object
                  properties:
                    profile:
                      type: string
                templates:
                  type: object
                  properties:
                    podTemplate:
                      type: string
                    volumeClaimTemplate:
                      type: string
            configuration:
              type: object
              required:
                - clusters
              properties:
                zookeeper:
                  type: object
                  properties:
                    nodes:
                      type: array
                      items:
                        type: object
                        required:
                          - host
                        properties:
                          host:
                            type: string
                          port:
                            type: integer
                            minimum: 1
                users:
                  type: object
                profiles:
                  type: object
                quotas:
                  type: object
                settings:
                  type: object
                clusters:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - layout
                    properties:
                      name:
                        type: string
                      shardsCount:
                        type: integer
                        minimum: 1
                      replicasCount:
                        type: integer
                        minimum: 1
                      templates:
                        type: object
                        properties:
                          podTemplate:
                            type: string
                          volumeClaimTemplate:
                            type: string
                      layout:
                        type: object
                        properties:
                          # DEPRECATED - to be removed soon
                          type:
                            enum:
                              - Standard
                              - Advanced
                          shardsCount:
                            type: integer
                          replicasCount:
                            type: integer
                          shards:
                            type: array
                            items:
                              type: object
                              properties:
                                name:
                                  type: string
                                # DEPRECATED - to be removed soon
                                definitionType:
                                  enum:
                                    - ReplicasCount
                                    - Replicas
                                replicasCount:
                                  type: integer
                                  minimum: 1
                                weight:
                                  type: integer
                                internalReplication:
                                  enum:
                                    - 0
                                    - 1
                                    - False
                                    - True
                                    - No
                                    - Yes
                                    - Off
                                    - On
                                    - Disabled
                                    - Enabled
                                templates:
                                  type: object
                                  properties:
                                    podTemplate:
                                      type: string
                                    volumeClaimTemplate:
                                      type: string
                                replicas:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      name:
                                        type: string
                                      port:
                                        type: integer
                                        minimum: 1
                                      templates:
                                        type: object
                                        properties:
                                          podTemplate:
                                            type: string
                                          volumeClaimTemplate:
                                            type: string
            templates:
              type: object
              properties:
                volumeClaimTemplates:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - spec
                    properties:
                      name:
                        type: string
                      spec:
                        # TODO specify PersistentVolumeClaimSpec
                        type: object
                podTemplates:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - spec
                    properies:
                      name:
                        type: string
                      spec:
                        # TODO specify PodSpec
                        type: object
---
# Setup ServiceAccount
# ServiceAccount would be created in kubectl-specified namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clickhouse-operator
  namespace: kube-system
---
# Setup ClusterRoleBinding between ClusterRole and ServiceAccount.
# ClusterRoleBinding is namespace-less and must have unique name
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clickhouse-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: clickhouse-operator
    namespace: kube-system
---
# Setup ClusterIP Service to provide monitoring metrics for Prometheus
# Service would be created in kubectl-specified namespace
# In order to get access outside of k8s it should be exposed as:
# kubectl --namespace prometheus port-forward service/prometheus 9090
# and point browser to localhost:9090
kind: Service
apiVersion: v1
metadata:
  name: clickhouse-operator-metrics
  namespace: kube-system
  labels:
    app: clickhouse-operator
spec:
  ports:
    - port: 8888
      name: clickhouse-operator-metrics
  selector:
    app: clickhouse-operator
---
# Possible Template Parameters:
#
# kube-system
# altinity/clickhouse-operator:latest
#
# Setup Deployment for clickhouse-operator
# Deployment would be created in kubectl-specified namespace
kind: Deployment
apiVersion: apps/v1
metadata:
  name: clickhouse-operator
  namespace: kube-system
  labels:
    app: clickhouse-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse-operator
  template:
    metadata:
      labels:
        app: clickhouse-operator
    spec:
      serviceAccountName: clickhouse-operator
      containers:
        - name: clickhouse-operator
          image: altinity/clickhouse-operator:latest
          env:
            # Pod-specific
            # spec.nodeName: ip-172-20-52-62.ec2.internal
            - name: OPERATOR_POD_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # metadata.name: clickhouse-operator-6f87589dbb-ftcsf
            - name: OPERATOR_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            # metadata.namespace: kube-system
            - name: OPERATOR_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            # status.podIP: 100.96.3.2
            - name: OPERATOR_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            # spec.serviceAccount: clickhouse-operator
            # spec.serviceAccountName: clickhouse-operator
            - name: OPERATOR_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName

            # Container-specific
            - name: OPERATOR_CONTAINER_CPU_REQUEST
              valueFrom:
                resourceFieldRef:
                  containerName: clickhouse-operator
                  resource: requests.cpu
            - name: OPERATOR_CONTAINER_CPU_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: clickhouse-operator
                  resource: limits.cpu
            - name: OPERATOR_CONTAINER_MEM_REQUEST
              valueFrom:
                resourceFieldRef:
                  containerName: clickhouse-operator
                  resource: requests.memory
            - name: OPERATOR_CONTAINER_MEM_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: clickhouse-operator
                  resource: limits.memory
