apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "standard-04"
spec:
  configuration:
    clusters:
      - name: "standard-04-not-sharded-replicated"
        layout:
          type: Standard
          shardsCount: 1
          replicasCount: 2
      - name: "standard-04-sharded-not-replicated"
        layout:
          type: Standard
          shardsCount: 2
      - name: "standard-04-sharded-replicated"
        layout:
          type: Standard
          replicasCount: 2
