apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "standard-02-deployment-pv"
spec:
  configuration:
    clusters:
      - name: "standard-02-deployment-pv"
        deployment:
          podTemplate: clickhouse-with-volume-template
          volumeClaimTemplate: clickhouse-storage-template
        layout:
          type: Standard
          shardsCount: 1
          replicasCount: 1
  templates:
    podTemplates:
      - name: clickhouse-with-volume-template
        containers:
          - name: clickhouse-pod
            image: yandex/clickhouse-server:19.3.7
            ports:
              - name: http
                containerPort: 8123
              - name: client
                containerPort: 9000
              - name: interserver
                containerPort: 9009
            volumeMounts:
              - name: clickhouse-storage
                mountPath: /var/lib/clickhouse
    volumeClaimTemplates:
      - name: clickhouse-storage-template
        persistentVolumeClaim:
          metadata:
            name: clickhouse-storage
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
