apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "syandard-02-multicluster"
spec:
  defaults:
    templates:
      volumeClaimTemplate: auto-simple-vc
  configuration:
    clusters:
      - name: "sharded-replicated"
        layout:
          shardsCount: 1
          replicasCount: 2
      - name: "sharded-non-replicated"
        layout:
          shardsCount: 2
      - name: "replicated"
        layout:
          replicasCount: 2
  templates:
    volumeClaimTemplates:
    - name: auto-simple-vc
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 123Mi
