apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "template-01"
spec:
  defaults:
    deployment:
      podTemplate: customPodTemplate
      volumeClaimTemplate: customVolumeClaimTemplate

  templates:
    volumeClaimTemplates:
    - name: customVolumeClaimTemplate
      persistentVolumeClaim:
        metadata:
          name: clickhouse-data-test
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi

    podTemplates:
    - name: customPodTemplate
      containers:
      - name: clickhouse
        volumeMounts:
        - name: clickhouse-data-test
          mountPath: /var/lib/clickhouse
        image: yandex/clickhouse-server:18.16.1
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "500m"

  configuration:
    clusters:
      - name: "sharded-replicated"
        layout:
          type: Standard
          shardsCount: 1
          replicasCount: 2
      - name: "sharded-non-replicated"
        layout:
          type: Standard
          shardsCount: 2
      - name: "replicated"
        layout:
          type: Standard
          replicasCount: 2