apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "repl-03"
spec:
  configuration:
    zookeeper:
      nodes:
      - host: zookeeper.zoo1ns
        port: 2181
    clusters:
    - name: replcluster
      deployment:
        podTemplate: clickhouse-with-volume-template
        volumeClaimTemplate: clickhouse-storage-template
      layout:
        type: Standard
        shardsCount: 1
        replicasCount: 2
  templates:
    podTemplates:
    - name: clickhouse-with-volume-template
      # volumes:
      containers:
      - name: clickhouse-pod
        image: yandex/clickhouse-server:19.3.7
        ports:
        - name: rest
          containerPort: 8123
        - name: rpc
          containerPort: 9000
        - name: interserver
          containerPort: 9009
        volumeMounts:
        - name: clickhouse-storage
          mountPath: /var/lib/clickhouse
    volumeClaimTemplates:
    - name: clickhouse-storage-template
      persistentVolumeClaim:
        metadata:
          name: clickhouse-storage
        spec:
          # no storageClassName - means use default storageClassName
          #storageClassName: default
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
