apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "advanced-layout"
spec:
  configuration:
    clusters:
    - name: adv
      layout:
        type: Advanced
        shards:
        - definitionType: Replicas
          replicas:
          - deployment:
              podTemplate: clickhouse:19.1.10
          - deployment:
              podTemplate: clickhouse:19.3.5
          - deployment:
              podTemplate: clickhouse:19.3.7

  templates:
    podTemplates:
    - name: clickhouse:19.3.7
      # volumes:
      containers:
      - name: clickhouse-pod
#        image: yandex/clickhouse-server:19.3.5
        image: yandex/clickhouse-server:19.3.7
#        image: yandex/clickhouse-server:19.1.10
#        image: yandex/clickhouse-server:19.1.105
        ports:
        - name: http
          containerPort: 8123
        - name: client
          containerPort: 9000
        - name: interserver
          containerPort: 9009

    - name: clickhouse:19.3.5
      # volumes:
      containers:
      - name: clickhouse-pod
#        image: yandex/clickhouse-server:19.3.5
        image: yandex/clickhouse-server:19.3.7
#        image: yandex/clickhouse-server:19.1.10
#        image: yandex/clickhouse-server:19.1.105
        ports:
        - name: http
          containerPort: 8123
        - name: client
          containerPort: 9000
        - name: interserver
          containerPort: 9009

    - name: clickhouse:19.1.10
      # volumes:
      containers:
      - name: clickhouse-pod
#        image: yandex/clickhouse-server:19.3.5
        image: yandex/clickhouse-server:19.3.7
#        image: yandex/clickhouse-server:19.1.10
#        image: yandex/clickhouse-server:19.1.105
        ports:
        - name: http
          containerPort: 8123
        - name: client
          containerPort: 9000
        - name: interserver
          containerPort: 9009
