apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "verityprod"
  namespace: dev
spec:
  defaults:
    replicasUseFQDN: "0"
    distributedDDL:
      profile: default
    templates:
      podTemplate: clickhouse-template
      volumeClaimTemplate: aws-ebs-volume-claim
      serviceTemplate: chi-service-template

  configuration:
    settings:
      compression/case/method: zstd
    users:
      verity_prod/password: "verity"
      verity_prod/networks/ip: "::/0"
      verity_prod/profile: "default"
      verity_prod/allow_databases/database:
        - "veritytest"
        - "verityprod"
    clusters:
      - name: replicas-only
        templates:
          podTemplate: clickhouse-template
          volumeClaimTemplate: aws-ebs-volume-claim
        layout:
          replicasCount: 1

  templates:
    serviceTemplates:
      - name: chi-service-template
        generateName: "service-{chi}"
        metadata:
          annotations:
            external-dns.alpha.kubernetes.io/hostname: XXXXXXXXXXXXXXXXXXXX.
            service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
            service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
            service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS-1-2-2017-01
        spec:
          ports:
            - name: http
              port: 8123
            - name: client
              port: 9000
          type: LoadBalancer

    volumeClaimTemplates:
      - name: aws-ebs-volume-claim
        spec:
#          storageClassName: ebs-volume-class
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi

    podTemplates:
      - name: clickhouse-template
        metadata:
          labels:
            app: clickhouse
        spec:
          containers:
            - name: clickhouse
              image: yandex/clickhouse-server
              ports:
                - name: http
                  containerPort: 8123
                - name: client
                  containerPort: 9000
              volumeMounts:
                - name: aws-ebs-volume-claim
                  mountPath: /var/lib/clickhouse
#          nodeSelector:
#            beta.kubernetes.io/instance-type: r5a.xlarge

