apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallationTemplate"
metadata:
  name: "simple-template-01"
spec:
  defaults:
    templates:
      volumeClaimTemplate: volumeclaim-template
  templates:
    volumeClaimTemplates:
      - name: volumeclaim-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi

