apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "test4"
spec:
  configuration:
    users:
      readonly/profile: readonly
      test/profile: default
      test/quota: default
    profiles:
      default/max_memory_usage: "1000000000"
      readonly/readonly: "1"
    quotas:
      default/interval/duration: "3600"
    settings:
      compression/case/method: zstd
    clusters:
      - name: "sharded-replicated"
        layout:
          type: Standard
          shardsCount: 1
          replicasCount: 2
      - name: "sharded-non-replicated"
        layout:
          type: Standard
          shardsCount: 2
      - name: "replicated"
        layout:
          type: Standard
          replicasCount: 2