apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "test1"
spec:
  configuration:
    clusters:
      - name: "sharded-replicated"
        layout:
          type: Standard
          shardsCount: 1
          replicasCount: 2
      - name: "sharded-non-replicated"
        layout:
          type: Standard
          shardsCount: 2
      - name: "replicated"
        layout:
          type: Standard
          replicasCount: 2