kind: PersistentVolume
apiVersion: v1
metadata:
  name: chi-test-pv-volume
  labels:
    clickhouse.altinity.com/chi: test1
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"