version: 2
jobs:
  build:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Building Docker images
          command: |
            echo 'export CHO_RELEASE=$(cat release)' >> $BASH_ENV
            docker build -f dockerfile/operator/Dockerfile -t clickhouse-operator:latest .
            docker build -f dockerfile/metrics-exporter/Dockerfile -t metrics-exporter:latest .
  deploy_release:
    machine:
      enabled: true
    steps:
      - run:
          name: Pushing Docker image
          command: |
            echo 'export CHO_RELEASE=$(cat release)' >> $BASH_ENV
            docker tag clickhouse-operator:latest $COMPANY_REPO/clickhouse-operator:latest
            docker tag clickhouse-operator:latest $COMPANY_REPO/clickhouse-operator:$CHO_RELEASE
            docker tag metrics-exporter:latest $COMPANY_REPO/metrics-exporter:latest
            docker tag metrics-exporter:latest $COMPANY_REPO/metrics-exporter:$CHO_RELEASE

            docker login -u $DOCKER_USER -p $DOCKER_PASS

            docker push $COMPANY_REPO/clickhouse-operator:latest
            docker push $COMPANY_REPO/clickhouse-operator:$CHO_RELEASE
            docker push $COMPANY_REPO/metrics-exporter:latest
            docker push $COMPANY_REPO/metrics-exporter:$CHO_RELEASE
  deploy_dev:
    machine:
      enabled: true
    steps:
      - run:
          requires: build
          name: Pushing Docker image
          command: |
            docker tag clickhouse-operator:latest $COMPANY_REPO/clickhouse-operator:dev
            docker tag metrics-exporter:latest $COMPANY_REPO/metrics-exporter:dev

            docker login -u $DOCKER_USER -p $DOCKER_PASS

            docker push $COMPANY_REPO/clickhouse-operator:dev
            docker push $COMPANY_REPO/metrics-exporter:dev
workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - vladislav-dev
      - deploy_release:
          requires: 
            - build
          filters:
            branches:
              only: master
      - deploy_dev:
          requires: 
            - build
          filters:
            branches:
              ignore:
                - master
