version: 2.0
jobs:
  build:
    branches:
      only:
        - master
    machine:
      enabled: true
      # docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Building Docker images
          command: |
            echo 'export CHO_RELEASE=$(cat release)' >> $BASH_ENV
            docker build -f dockerfile/operator/Dockerfile -t clickhouse-operator:latest .
            docker build -f dockerfile/metrics-exporter/Dockerfile -t metrics-exporter:latest .
      - run:
          name: Pushing Docker image
          command: |
            docker tag clickhouse-operator:latest $COMPANY_REPO/clickhouse-operator:latest
            docker tag clickhouse-operator:latest $COMPANY_REPO/clickhouse-operator:$CHO_RELEASE
            docker tag metrics-exporter:latest $COMPANY_REPO/metrics-exporter:latest
            docker tag metrics-exporter:latest $COMPANY_REPO/metrics-exporter:$CHO_RELEASE

            docker login -u $DOCKER_USER -p $DOCKER_PASS

            docker push $COMPANY_REPO/clickhouse-operator:latest
            docker push $COMPANY_REPO/clickhouse-operator:$CHO_RELEASE
            docker push $COMPANY_REPO/metrics-exporter:latest
            docker push $COMPANY_REPO/metrics-exporter:$CHO_RELEASE
