# Setup ServiceMonitor to monitor clickhouse-operator metrics end-point by Prometheus
# ServiceMonitor would be created in kubectl-specified namespace
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zookeeper
  labels:
    app: prometheus
    service: zookeeper
spec:
  # IMPORTANT
  # Specify namespaces where zookeeper service is located
  namespaceSelector:
     any: true
  # Specify labels of zookeeper service
  selector:
    matchLabels:
      app: zookeeper
  # Specify which labels will stored in prometheus from service
  targetLabels:
    - app
  # Specify port where zookeeper service prometheus /metrics  listens
  endpoints:
    # This is port name from `zookeeper` service (it is the same as service name in there)
    - port: prometheus
#    - targetPort: 8888
#      interval: 10s
#      scheme: http
