apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "repl-06"
spec:
  configuration:
    zookeeper:
      nodes:
        - host: zookeeper-0.zookeepers.zoo3ns
          port: 2181
        - host: zookeeper-1.zookeepers.zoo3ns
          port: 2181
        - host: zookeeper-2.zookeepers.zoo3ns
          port: 2181
      session_timeout_ms: 30000
      operation_timeout_ms: 10000
      root: /path/to/zookeeper/node
      identity: user:password
    clusters:
      - name: replcluster1
        layout:
          shardsCount: 3
          replicasCount: 2
      - name: replcluster2
        zookeeper:
          nodes:
            - host: zookeeper-0.zookeepers.zoo5ns
              port: 2181
            - host: zookeeper-1.zookeepers.zoo5ns
              port: 2181
            - host: zookeeper-2.zookeepers.zoo5ns
              port: 2181
            - host: zookeeper-3.zookeepers.zoo5ns
              port: 2181
            - host: zookeeper-4.zookeepers.zoo5ns
              port: 2181
        layout:
          shardsCount: 3
          replicasCount: 2
