apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "settings-nested"
spec:
  configuration:
    settings:
      disable_internal_dns_cache: 1
    clusters:
      - name: "standard"
        layout:
          shardsCount: 1
          replicasCount: 1
