apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "hostnet1"
spec:
  defaults:
    templates:
      hostTemplate: port-distribution
      podTemplate: pod-distribution

  configuration:
    clusters:
      - name: "hnet1"
        layout:
          shardsCount: 3
          replicasCount: 3

  templates:
    hostTemplates:
      - name: port-distribution
        portDistribution:
          - type: ClusterScopeIndex
        spec:
          tcpPort: 10000
          httpPort: 11000
          interserverHTTPPort: 12000

    podTemplates:
      - name: pod-distribution
        podDistribution:
          - type: CircularReplication
        spec:
          hostNetwork: true
          containers:
            - name: clickhouse
              image: yandex/clickhouse-server:18.16.1
