apiVersion: "clickhouse.example.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "test"
spec:
  configuration:
    clusters:
      - name: "sharded-replicated"
        layout:
          type: Standard
          shardsCount: 2
          replicasCount: 3
      - name: "sharded-non-replicated"
        layout:
          type: Standard
          shardsCount: 2
      - name: "replicated"
        layout:
          type: Standard
          replicasCount: 4