namespaces:
  - dev
  - info
  - onemore

chCommonConfigsPath: config.d
chDeploymentConfigsPath: conf.d
chUsersConfigsPath: users.d
chiTemplatesPath: templates.d

statefulSetUpdateTimeout: 50
statefulSetUpdatePollPeriod: 2
onStatefulSetUpdateFailureAction: abort
