apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "template1"
spec:
  defaults:
    replicasUseFQDN: 0 # 0 - by default, 1 - enabled
    distributedDDL:
      profile: default
    deployment:
      zone:
        matchLabels:
          clickhouse.altinity.com/zone: zone1
      podTemplate: clickhouse-v18.16.1
      volumeClaimTemplate: default
  configuration:
    zookeeper:
      nodes:
        - host: zk-statefulset-0.zk-service.default.svc.cluster.local
          port: 2181
        - host: zk-statefulset-1.zk-service.default.svc.cluster.local
          port: 2181
        - host: zk-statefulset-2.zk-service.default.svc.cluster.local
          port: 2181
    users:
      test/profile: default
      test/quotas: default
      readonly/profile: readonly
    profiles:
      readonly/readonly: "1"
      default/max_memory_usage: "1000000000"
    quotas:
      default/interval/duration: "3600"
    settings:
      compression/case/method: zstd
  templates:
    podTemplates:
      - name: clickhouse-v18.16.1
        containers:
          - name: clickhouse
            image: yandex/clickhouse-server:18.16.1
            volumeMounts:
              - name: clickhouse-data-test
                mountPath: /var/lib/clickhouse
      - name: clickhouse-v18.16.2
        containers:
          - name: clickhouse
            image: yandex/clickhouse-server:18.16.2
            volumeMounts:
              - name: clickhouse-data-test
                mountPath: /var/lib/clickhouse
